services:
  backend-flask:
    image: leo592/lms-backend:2.0.0
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    networks:
      - app-network

  frontend:
    image: leo592/lms-frontend:2.0.0
    ports:
      - "80:80" # Changed to port 80 for Nginx
    depends_on:
      - backend-flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
